### ISSUE TITLE
js与css放置的位置问题 - detectiveHLH

### ISSUE THREAD

**Issue by detectiveHLH** [detectiveHLH/detectiveHLH.github.io#3]
https://detectivehlh.github.io/2016/09/13/%E5%89%8D%E7%AB%AF/js%E4%B8%8Ecss%E6%94%BE%E7%BD%AE%E7%9A%84%E4%BD%8D%E7%BD%AE%E9%97%AE%E9%A2%98/

**Comment by detectiveHLH** [comment]
很早之前的文章

**Comment by chendi20082009** [comment]
不错哦~

**Comment by chendi20082009** [comment]
为什么我的头像在这里显示是正常的，而在我自己的博客中显示就是不正常的？

**Comment by detectiveHLH** [comment]
你确定正确的接入了github的application

**Comment by chendi20082009** [comment]
是的呀，能用，但是就是头像是遍的，不知道为啥？
![image](https://user-images.githubusercontent.com/10103354/43948710-24bc63b2-9cbe-11e8-85f6-4e306a5aef0d.png)

**Comment by detectiveHLH** [comment]
添加gitment的时候有加css，你看看是不是没有加对，或者是有其他的覆盖了

**Comment by chendi20082009** [comment]
嗯呢，我找找原因的。
